# SPDX-License-Identifier: BSD-3-Clause

from SCons.Script import File


Import("Sources")
Import("CoreFsSources")
Import("CoreFsSharedSources")

Sources += [
    File("fat.c"),
    File("ext2.c"),
    File("iso9660.c"),
    File("mbr.c"),
    File("gpt.c"),
]
CoreFsSources += [
    File("fat.c"),
    File("ext2.c"),
    File("iso9660.c"),
]
CoreFsSharedSources += [
    File("mbr.c"),
    File("gpt.c"),
]
