target-version = "py312"
line-length = 88
indent-width = 4

[lint]
select = ["E9", "F63", "F7", "F82"]
ignore = ["ALL"]

[format]
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = false