# SPDX-License-Identifier: BSD-3-Clause

from SCons.Script import File


Import("Sources")
Import("CoreFsSources")
Import("CoreFsSharedSources")

SConscript("fs/SConscript", exports=["Sources", "CoreFsSources", "CoreFsSharedSources"])
SConscript("dl/SConscript", exports=["CoreFsSources"])
