repos:
-   repo: local
    hooks:
    -   id: valecium-formatter
        name: Valecium Formatter
        entry: python3 scripts/base/format.py
        language: system
        pass_filenames: false
    -   id: scons-dry-run
        name: SCons Syntax Check
        entry: scons -n -Q
        language: system
        pass_filenames: false
        always_run: true
