# SPDX-License-Identifier: BSD-3-Clause
"""
Bootloader build configuration.
"""

import os

from SCons.Environment import Environment
from SCons.Script import Dir, Export, SConscript

from scripts.scons.arch import GetArchConfig
from scripts.scons.bootloader import (
    ConfigureBootloaderEnvironment,
    GetBootloaderBuildConfig,
)


Import("TargetEnvironment")
TargetEnvironment: Environment

# =============================================================================
# Environment Setup
# =============================================================================

MainEnvironment = TargetEnvironment.Clone()

SourcePath = Dir("#boot").abspath
Architecture = TargetEnvironment["BuildArch"]
BootType = TargetEnvironment["BootType"]
ProjectVersion = TargetEnvironment["ProjVersion"]
ArchitecturePath = os.path.join(SourcePath, BootType, Architecture)

ArchitectureConfig = GetArchConfig(Architecture)
BuildConfig = TargetEnvironment["BuildConfig"]
BootloaderBuildConfig = GetBootloaderBuildConfig(
    BootType, Architecture, ProjectVersion, BuildConfig
)

ConfigureBootloaderEnvironment(
    MainEnvironment,
    SourcePath,
    ArchitecturePath,
    ArchitectureConfig,
    BootloaderBuildConfig,
)

# =============================================================================
# Source Files
# =============================================================================

Sources = []
CoreFsSources = []
CoreFsSharedSources = []
SConscript(
    "common/SConscript", exports=["Sources", "CoreFsSources", "CoreFsSharedSources"]
)

# =============================================================================
# Bootloader Components
# =============================================================================

TargetEnvironment["BootloaderComponents"]["BootType"] = BootType
TargetEnvironment["BootloaderComponents"]["Architecture"] = Architecture

if BootType == "bios":
    SConscript(
        "bios/SConscript",
        exports=[
            "TargetEnvironment",
            "SourcePath",
            "ArchitecturePath",
            "ArchitectureConfig",
            "BootloaderBuildConfig",
            "Sources",
            "CoreFsSources",
            "CoreFsSharedSources",
            "Architecture",
        ],
    )
elif BootType == "efi":
    SConscript(
        "efi/SConscript",
        exports=[
            "TargetEnvironment",
            "SourcePath",
            "ArchitecturePath",
            "ArchitectureConfig",
            "BootloaderBuildConfig",
            "Sources",
            "CoreFsSharedSources",
            "Architecture",
        ],
    )
else:
    raise RuntimeError(f"Unsupported boot type: {BootType}")

# =============================================================================
# Build Target
# =============================================================================

MainEnvironment.Append(OBJPREFIX="main_")
Objects = MainEnvironment.SharedObject(Sources)

Bootloader = MainEnvironment.SharedLibrary(BootloaderBuildConfig["OutputName"], Objects)
TargetEnvironment["BootloaderComponents"]["Main"] = Bootloader

Export("Bootloader")
