# SPDX-License-Identifier: BSD-3-Clause

from SCons.Script import File


Import('Sources')
Import('CoreFsSources')

Sources += [
    File('fat.c'),
    File('ext2.c'),
]
CoreFsSources += [
    File('fat.c'),
    File('ext2.c'),
]