# SPDX-License-Identifier: BSD-3-Clause

from SCons.Script import File, Return


Import("Sources")
Import("CoreSources")


Sources += [
    File("i686.S"),
]

CoreSources += [
    File("i686.S"),
    File("core.S"),
    File("detect.S"),
]


Result = {
    "BootSector": File("boot.S"),
    "CoreFsDiskSource": File("disk.S"),
    "CoreFsLinkerScript": File("corefs.ld").srcnode(),
}
Return("Result")
