#!/opt/local/bin/python3
"""Generate the Valecium boot logo C header from the source PNG.

Usage: mklogo.py <logo_gen.h>

Output: 640x640, 3 colours (white, blue, black), 4bpp format.
"""

import sys
import os
from PIL import Image

ScriptDir = os.path.dirname(os.path.abspath(__file__))
RepoRoot = os.path.normpath(os.path.join(ScriptDir, "..", "..", ".."))
SrcPng = os.path.join(RepoRoot, "Documentation", "assets", "ValeciumOS.png")

if len(sys.argv) < 2:
    print("Usage: mklogo.py <logo_gen.h>")
    sys.exit(1)

OutH = sys.argv[1]

# Target colours (R, G, B)
WhiteColour = (252, 252, 252)
BlueColour = (228, 250, 254)
BlackColour = (0, 0, 0)
Colours = [WhiteColour, BlueColour, BlackColour]

LogoW = 640
LogoH = 640

# ---------------------------------------------------------------------------


def NearestColour(r, g, b):
    """Return index 0 (white), 1 (blue), or 2 (black) for the closest colour."""
    Best = 0
    BestDist = 3 * 256 * 256
    for i, (Cr, Cg, Cb) in enumerate(Colours):
        D = (r - Cr) * (r - Cr) + (g - Cg) * (g - Cg) + (b - Cb) * (b - Cb)
        if D < BestDist:
            BestDist = D
            Best = i
    return Best


def QuantizeTo3Colours(Img):
    """Map every pixel to the nearest of the 3 target colours."""
    Out = Image.new("P", Img.size)
    Pixels = Img.load()
    OPixels = Out.load()
    W, H = Img.size
    for y in range(H):
        for x in range(W):
            R, G, B, A = Pixels[x, y][:4]
            if A < 128:
                OPixels[x, y] = 2  # transparent -> black
            else:
                OPixels[x, y] = NearestColour(R, G, B)
    return Out


def Pack4Bpp(Pixels, W, H):
    """Pack 4-bit pixel indices into a byte array (2 pixels per byte)."""
    Data = bytearray((W * H + 1) // 2)
    for i, Val in enumerate(Pixels):
        if Val & ~0x0F:
            raise ValueError(f"Pixel value {Val} out of range for 4bpp")
        ByteIdx = i >> 1
        if i & 1:
            Data[ByteIdx] |= Val  # low nibble
        else:
            Data[ByteIdx] |= Val << 4  # high nibble
    return Data


def FormatCArray(Data, Width=16):
    """Format bytes as a C literal."""
    Lines = []
    for i in range(0, len(Data), Width):
        Chunk = Data[i : i + Width]
        HexStr = ", ".join(f"0x{b:02X}" for b in Chunk)
        Lines.append(f"   {HexStr}, ")
    return "\n".join(Lines)


def main():
    Src = Image.open(SrcPng).convert("RGBA")
    Sw, Sh = Src.size

    # --- crop to centred square -------------------------------------------------
    Size = min(Sw, Sh)
    Left = (Sw - Size) // 2
    Top = (Sh - Size) // 2
    Square = Src.crop((Left, Top, Left + Size, Top + Size))

    # --- quantise to 3 colours --------------------------------------------------
    Quant = QuantizeTo3Colours(Square)

    # --- resize to output size (NEAREST keeps edges sharp) ----------------------
    Final = Quant.resize((LogoW, LogoH), Image.NEAREST)

    # --- pack to 4bpp -----------------------------------------------------------
    Pixels = Final.getdata()
    Data = Pack4Bpp(Pixels, LogoW, LogoH)

    # --- write C header ---------------------------------------------------------
    DataStr = FormatCArray(Data)
    PalStr = ", ".join(f"0x{r:02X}, 0x{g:02X}, 0x{b:02X}" for r, g, b in Colours)

    header = f"""// Auto-generated by {os.path.basename(__file__)} from {os.path.relpath(SrcPng, RepoRoot)}
// 3 colours, {LogoW}x{LogoH}, 4bpp
#pragma once

#include <stdint.h>

#define VALECIUM_LOGO_W {LogoW}
#define VALECIUM_LOGO_H {LogoH}
#define VALECIUM_LOGO_PALETTE_SIZE {len(Colours)}

static const uint8_t s_ValeciumLogo_PaletteRGB[] = {{
   {PalStr}
}};

static const uint8_t s_ValeciumLogo_Data4bpp[] = {{
{DataStr}
}};
"""

    with open(OutH, "w") as f:
        f.write(header)


if __name__ == "__main__":
    main()
