#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""
Generate ISR stub C and assembly files for i686.

Usage: mkisrs.py <isrs_gen.c> <isrs_gen.inc>
"""

import sys


def GenerateC(IsrsWithErrorCode: set[int]) -> str:
    Parts = [
        "// !!! THIS FILE IS AUTOGENERATED !!!",
        "#include <arch/i686/cpu/idt.h>",
        "#include <arch/i686/cpu/gdt.h>",
        "",
    ]

    # Extern declarations
    for i in range(256):
        Parts.append(f"void __attribute((cdecl)) i686_ISR{i}();")

    Parts += [
        "",
        "void i686_ISR_InitializeGates()",
        "{",
    ]

    # IDT gate setup
    for i in range(256):
        Parts.append(
            f"    i686_IDT_SetGate({i}, i686_ISR{i}, "
            f"i686_GDT_CODE_SEGMENT, IDT_FLAG_RING0 | IDT_FLAG_GATE_32BIT_INT);"
        )

    Parts.append("}")
    return "\n".join(Parts) + "\n"


def GenerateAsm(IsrsWithErrorCode: set[int]) -> str:
    Parts = ["# THIS FILE IS AUTOGENERATED"]
    for i in range(256):
        Macro = "ISR_ERRORCODE" if i in IsrsWithErrorCode else "ISR_NOERRORCODE"
        Parts.append(f"{Macro} {i}")
    return "\n".join(Parts) + "\n"


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <isrs_gen.c> <isrs_gen.inc>", file=sys.stderr)
        sys.exit(1)

    IsrsGenC = sys.argv[1]
    IsrsGenAsm = sys.argv[2]

    IsrsWithErrorCode = {8, 10, 11, 12, 13, 14, 17, 21}

    CCode = GenerateC(IsrsWithErrorCode)
    AsmCode = GenerateAsm(IsrsWithErrorCode)

    with open(IsrsGenC, "w") as f:
        f.write(CCode)
    with open(IsrsGenAsm, "w") as f:
        f.write(AsmCode)


if __name__ == "__main__":
    main()
