#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""
Generate ISR stub C and assembly files for i686.

Usage: mkisrs.py <isrs_gen.c> <isrs_gen.inc>
"""

import sys


def generate_c(isrs_with_error_code: set[int]) -> str:
    parts = [
        '// !!! THIS FILE IS AUTOGENERATED !!!',
        '#include <arch/i686/cpu/idt.h>',
        '#include <arch/i686/cpu/gdt.h>',
        '',
    ]

    # Extern declarations
    for i in range(256):
        parts.append(f'void __attribute((cdecl)) i686_ISR{i}();')

    parts += [
        '',
        'void i686_ISR_InitializeGates()',
        '{',
    ]

    # IDT gate setup
    for i in range(256):
        parts.append(
            f'    i686_IDT_SetGate({i}, i686_ISR{i}, '
            f'i686_GDT_CODE_SEGMENT, IDT_FLAG_RING0 | IDT_FLAG_GATE_32BIT_INT);'
        )

    parts.append('}')
    return '\n'.join(parts) + '\n'


def generate_asm(isrs_with_error_code: set[int]) -> str:
    parts = ['# THIS FILE IS AUTOGENERATED']
    for i in range(256):
        macro = 'ISR_ERRORCODE' if i in isrs_with_error_code else 'ISR_NOERRORCODE'
        parts.append(f'{macro} {i}')
    return '\n'.join(parts) + '\n'


def main():
    if len(sys.argv) < 3:
        print(f'Usage: {sys.argv[0]} <isrs_gen.c> <isrs_gen.inc>', file=sys.stderr)
        sys.exit(1)

    isrs_gen_c = sys.argv[1]
    isrs_gen_asm = sys.argv[2]

    isrs_with_error_code = {8, 10, 11, 12, 13, 14, 17, 21}

    c_code = generate_c(isrs_with_error_code)
    asm_code = generate_asm(isrs_with_error_code)

    with open(isrs_gen_c, 'w') as f:
        f.write(c_code)
    with open(isrs_gen_asm, 'w') as f:
        f.write(asm_code)


if __name__ == '__main__':
    main()
