# SPDX-License-Identifier: BSD-3-Clause
"""
EFI bootloader build configuration.
"""

from SCons.Script import SConscript
from scripts.scons.bootloader import ConfigureBootloaderEnvironment


Import("TargetEnvironment")
Import("SourcePath")
Import("ArchitecturePath")
Import("ArchitectureConfig")
Import("BootloaderBuildConfig")
Import("Architecture")
Import("Sources")


if Architecture == "i686":
    SConscript("i686/SConscript", exports="Sources")
elif Architecture == "x86_64":
    SConscript("x86_64/SConscript", exports="Sources")
elif Architecture == "aarch64":
    SConscript("aarch64/SConscript", exports="Sources")
else:
    raise RuntimeError(f"Unsupported EFI architecture: {Architecture}")

EfiBin = TargetEnvironment.File("boot.efi")
TargetEnvironment["BootloaderComponents"]["EfiBinary"] = EfiBin

EfiEnv = TargetEnvironment.Clone()
ConfigureBootloaderEnvironment(
    EfiEnv,
    SourcePath,
    ArchitecturePath,
    ArchitectureConfig,
    BootloaderBuildConfig,
)

EfiObjects = EfiEnv.Object(Sources)
EfiBinary = EfiEnv.Program(EfiBin, EfiObjects)
