# SPDX-License-Identifier: BSD-3-Clause

from SCons.Script import Dir, File

Import("CoreSources")

CoreSources += [
    File("font_gen.c"),
    File("serial.c"),
    File("vbe.c"),
    File("vga_text.c"),
    File("vga.c"),
    File("print.c"),
]
