# SPDX-License-Identifier: BSD-3-Clause

import os

from SCons.Script import SConscript
from scripts.scons.bootloader import ConfigureBootloaderEnvironment

Import('TargetEnvironment')
Import('SourcePath')
Import('ArchitecturePath')
Import('ArchitectureConfig')
Import('BootloaderBuildConfig')
Import('Architecture')
Import('Sources')
Import('BootBin')
Import('CoreBin')


LinkModeByArchitecture = {
    'i686': 'elf_i386',
    'x86_64': 'elf_x86_64',
}


CoreSources = []

SConscript('video/SConscript', exports=['Sources', 'CoreSources'])

if Architecture == 'i686':
    BootSector = SConscript('i686/SConscript', exports=['Sources', 'CoreSources'])
elif Architecture == 'x86_64':
    BootSector = SConscript('x86_64/SConscript', exports=['Sources', 'CoreSources'])
else:
    raise RuntimeError(f'Unsupported BIOS architecture: {Architecture}')

BootLinkerScript = TargetEnvironment.File(f'{Architecture}/boot.ld').srcnode()
CoreLinkerScript = TargetEnvironment.File(f'{Architecture}/core.ld').srcnode()
BootEnv = TargetEnvironment.Clone()
CoreEnv = TargetEnvironment.Clone()

ConfigureBootloaderEnvironment(
    BootEnv,
    SourcePath,
    ArchitecturePath,
    ArchitectureConfig,
    BootloaderBuildConfig,
)
ConfigureBootloaderEnvironment(
    CoreEnv,
    SourcePath,
    ArchitecturePath,
    ArchitectureConfig,
    BootloaderBuildConfig,
)

BootEnv.AppendUnique(LINKFLAGS=[
    '-nostdlib',
    '-Wl,-N',
    f'-Wl,-m,{LinkModeByArchitecture[Architecture]}',
    f'-Wl,-T,{BootLinkerScript.path}',
    '-Wl,--oformat,binary',
])
CoreEnv.AppendUnique(LINKFLAGS=[
    '-nostdlib',
    '-Wl,-N',
    f'-Wl,-m,{LinkModeByArchitecture[Architecture]}',
    f'-Wl,-T,{CoreLinkerScript.path}',
    '-Wl,--oformat,binary',
])
CoreEnv.Append(LIBS=['gcc'])

BootSectorObject = BootEnv.Object(BootSector)
CoreObjects = CoreEnv.Object(CoreSources)

BootSectorBinary = BootEnv.Program(
    BootBin,
    BootSectorObject,
)

CoreBinary = CoreEnv.Program(
    CoreBin,
    CoreObjects,
)

BootEnv.AddPostAction(
    BootSectorBinary,
    lambda target, source, env: (
        (_ for _ in ()).throw(
            RuntimeError(
                f'BIOS boot sector exceeds 0x1be bytes: {boot_sector_size} bytes'
            )
        )
        if (boot_sector_size := os.path.getsize(str(target[0]))) > 0x1BE
        else None
    ),
)

BootEnv.Depends(BootSectorBinary, BootLinkerScript)
CoreEnv.Depends(CoreBinary, CoreLinkerScript)

Export('BootSectorBinary', 'CoreBinary')
